const babiesArr = [
  {
    name: "Monroe Cannon",
    birthday: "04/30/2011",
    approximate_conception_date: "08/07/2010",
    mother: "Mariah Carey",
    gender: "female",
    twin: true,
  },
  {
    name: "Moroccan Cannon",
    birthday: "04/30/2011",
    approximate_conception_date: "08/07/2010",
    mother: "Mariah Carey",
    gender: "female",
    twin: true,
  },
  {
    name: "Golden 'Sagon' Cannon",
    birthday: "02/21/2017",
    approximate_conception_date: "05/31/2016",
    mother: "Brittany Bell",
    gender: "male",
    twin: false,
  },
  {
    name: "Powerful Queen Cannon",
    birthday: "12/28/2020",
    approximate_conception_date: "04/06/2020",
    mother: "Brittany Bell",
    gender: "female",
    twin: false,
  },
  {
    name: "Zillion Mixolydian Cannon",
    birthday: "06/16/2021",
    approximate_conception_date: "09/23/2020",
    mother: "Abby De La Rosa",
    gender: "male",
    twin: true,
  },
  {
    name: "Zillion Heir Cannon",
    birthday: "06/16/2021",
    approximate_conception_date: "09/23/2020",
    mother: "Abby De La Rosa",
    gender: "male",
    twin: true,
  },
  {
    name: "Zen Scott Cannon",
    birthday: "06/23/2021",
    approximate_conception_date: "09/30/2020",
    mother: "Alyssa Scott",
    gender: "male",
    twin: false,
  },
  {
    name: "Legendary Love Cannon",
    birthday: "06/28/2022",
    approximate_conception_date: "10/05/2021",
    mother: "Bre Tiesi",
    gender: "male",
    twin: false,
  },
  {
    name: "Onyx Ice Cole Cannon",
    birthday: "09/14/2022",
    approximate_conception_date: "12/21/2021",
    mother: "LaNisha Cole",
    gender: "female",
    twin: false,
  },
  {
    name: "Rise Messiah Cannon",
    birthday: "09/23/2022",
    approximate_conception_date: "12/30/2021",
    mother: "Brittany Bell",
    gender: "male",
    twin: false,
  },
  {
    name: "Beautiful Zeppelin Cannon",
    birthday: "11/11/2022",
    approximate_conception_date: "02/18/2022",
    mother: "Abby De La Rosa",
    gender: "female",
    twin: false,
  },
  {
    name: "Baby Cannon",
    birthday: "",
    approximate_conception_date: "03/10/2022",
    mother: "Alyssa Scott",
    gender: "unknown",
    twin: false,
  },
];

module.exports = { babiesArr };
