const babiesArr = [
  {
    name: "Monroe Cannon",
    birthday: "04/30/2011",
    gender: "female",
    twin: true,
    approximate_conception_date: "08/07/2010",
    mother: "Mariah Carey",
    mother_age_at_birth: 41,
    nick_cannon_age_at_birth: 30,
    current_child_with_mother: 1,
    total_children_with_mother: 2,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Moroccan Cannon",
    birthday: "04/30/2011",
    gender: "female",
    twin: true,
    approximate_conception_date: "08/07/2010",
    mother: "Mariah Carey",
    mother_age_at_birth: 41,
    nick_cannon_age_at_birth: 30,
    current_child_with_mother: 2,
    total_children_with_mother: 2,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Golden 'Sagon' Cannon",
    birthday: "02/21/2017",
    gender: "male",
    twin: false,
    approximate_conception_date: "05/31/2016",
    mother: "Brittany Bell",
    mother_age_at_birth: 29,
    nick_cannon_age_at_birth: 36,
    current_child_with_mother: 1,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Powerful Queen Cannon",
    birthday: "12/28/2020",
    gender: "female",
    twin: false,
    approximate_conception_date: "04/06/2020",
    mother: "Brittany Bell",
    mother_age_at_birth: 33,
    nick_cannon_age_at_birth: 40,
    current_child_with_mother: 2,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Zillion Mixolydian Cannon",
    birthday: "06/16/2021",
    gender: "male",
    twin: true,
    approximate_conception_date: "09/23/2020",
    mother: "Abby De La Rosa",
    mother_age_at_birth: 30,
    nick_cannon_age_at_birth: 40,
    current_child_with_mother: 1,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Zillion Heir Cannon",
    birthday: "06/16/2021",
    gender: "male",
    twin: true,
    approximate_conception_date: "09/23/2020",
    mother: "Abby De La Rosa",
    mother_age_at_birth: 30,
    nick_cannon_age_at_birth: 40,
    current_child_with_mother: 2,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Zen Scott Cannon",
    birthday: "06/23/2021",
    gender: "male",
    twin: false,
    approximate_conception_date: "09/30/2020",
    mother: "Alyssa Scott",
    mother_age_at_birth: 27,
    nick_cannon_age_at_birth: 40,
    current_child_with_mother: 1,
    total_children_with_mother: 2,
    status: {
      alive: false,
      date_of_passing: "12/05/2021",
      age: {
        years: 0,
        months: 5,
        days: 13,
      },
    },
  },
  {
    name: "Legendary Love Cannon",
    birthday: "06/28/2022",
    gender: "male",
    twin: false,
    approximate_conception_date: "10/05/2021",
    mother: "Bre Tiesi",
    mother_age_at_birth: 31,
    nick_cannon_age_at_birth: 41,
    current_child_with_mother: 1,
    total_children_with_mother: 1,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Onyx Ice Cole Cannon",
    birthday: "09/14/2022",
    gender: "female",
    twin: false,
    approximate_conception_date: "12/21/2021",
    mother: "LaNisha Cole",
    mother_age_at_birth: 40,
    nick_cannon_age_at_birth: 41,
    current_child_with_mother: 1,
    total_children_with_mother: 1,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Rise Messiah Cannon",
    birthday: "09/23/2022",
    gender: "male",
    twin: false,
    approximate_conception_date: "12/30/2021",
    mother: "Brittany Bell",
    mother_age_at_birth: 34,
    nick_cannon_age_at_birth: 41,
    current_child_with_mother: 3,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Beautiful Zeppelin Cannon",
    birthday: "11/11/2022",
    gender: "female",
    twin: false,
    approximate_conception_date: "02/18/2022",
    mother: "Abby De La Rosa",
    mother_age_at_birth: 32,
    nick_cannon_age_at_birth: 42,
    current_child_with_mother: 3,
    total_children_with_mother: 3,
    status: {
      alive: true,
      age: {},
    },
  },
  {
    name: "Halo Marie Cannon",
    birthday: "12/14/2022",
    gender: "female",
    twin: false,
    approximate_conception_date: "03/23/2022",
    mother: "Alyssa Scott",
    mother_age_at_birth: 29,
    nick_cannon_age_at_birth: 42,
    current_child_with_mother: 2,
    total_children_with_mother: 2,
    status: {
      alive: true,
      age: {},
    },
  },
];

module.exports = { babiesArr };
